export interface Product {
  id: string;
  name: string;
  brand: string;
  price: number;
  image: string;
  description: string;
  category: 'male' | 'female' | 'unisex';
  family: 'Woody' | 'Floral' | 'Citrus' | 'Fresh' | 'Amber' | 'Vanilla' | 'Aromatic' | 'Leather';
  intensity: 'EDT' | 'EDP' | 'EXTRAIT';
  scent: string[];
  volume: number;
  rating: number;
  reviews: number;
  inStock: boolean;
  isBestseller?: boolean;
  volume_prices?: { volume: number; price: number }[];
  sillage?: string;
  projection?: string;
  longevity?: string;
}

export const products: Product[] = [
  {
    id: '1',
    name: 'Cedar & Silk',
    brand: 'Luxure Parfum',
    price: 450000,
    image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=500&h=500&fit=crop',
    description: 'Aroma misterius dengan kombinasi kayu cedar dan vanilla yang elegan.',
    category: 'male',
    family: 'Woody',
    intensity: 'EDP',
    scent: ['Cedar', 'Vanilla', 'Musk'],
    volume: 100,
    rating: 4.8,
    reviews: 256,
    inStock: true,
    isBestseller: true,
  },
  {
    id: '2',
    name: 'Morning Mist',
    brand: 'Citrus Dreams',
    price: 380000,
    image: 'https://images.unsplash.com/photo-1571975414439-27d4b93f5f2d?w=500&h=500&fit=crop',
    description: 'Wewangian bunga mawar yang romantic dan fresh untuk wanita modern.',
    category: 'female',
    family: 'Citrus',
    intensity: 'EDP',
    scent: ['Lemon', 'Orange', 'Bergamot'],
    volume: 75,
    rating: 4.9,
    reviews: 482,
    inStock: true,
  },
  {
    id: '3',
    name: 'Amber Hearth',
    brand: 'Marine Scents',
    price: 320000,
    image: 'https://images.unsplash.com/photo-1506755855726-85d82b8b34ec?w=500&h=500&fit=crop',
    description: 'Kesegaran laut dengan sentuhan lemon dan garam laut yang menyegarkan.',
    category: 'unisex',
    family: 'Vanilla',
    intensity: 'EDT',
    scent: ['Amber', 'Sandalwood', 'Vanilla'],
    volume: 100,
    rating: 4.6,
    reviews: 198,
    inStock: true,
  },
  {
    id: '4',
    name: 'Oud Noir',
    brand: 'Luxure Parfum',
    price: 520000,
    image: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500&h=500&fit=crop',
    description: 'Intens dan sensual dengan notes amber dan oud yang mewah.',
    category: 'male',
    family: 'Woody',
    intensity: 'EXTRAIT',
    scent: ['Oud', 'Patchouli', 'Musk'],
    volume: 100,
    rating: 4.7,
    reviews: 315,
    inStock: true,
    isBestseller: true,
  },
  {
    id: '5',
    name: 'Rose Petals',
    brand: 'Gentlemen\'s Choice',
    price: 380000,
    image: 'https://images.unsplash.com/photo-1508737763-95b3d2e8c6b3?w=500&h=500&fit=crop',
    description: 'Fragrance maskulin dengan karakter bergamot, cedar, dan leather.',
    category: 'female',
    family: 'Floral',
    intensity: 'EDP',
    scent: ['Rose', 'Peony', 'Musk'],
    volume: 100,
    rating: 4.8,
    reviews: 429,
    inStock: true,
  },
  {
    id: '6',
    name: 'Spice Road',
    brand: 'Sweet Essence',
    price: 290000,
    image: 'https://images.unsplash.com/photo-1590894903068-b0c9f1299c0c?w=500&h=500&fit=crop',
    description: 'Manis dan hangat dengan notes vanilla cream dan caramel.',
    category: 'unisex',
    family: 'Vanilla',
    intensity: 'EDP',
    scent: ['Cinnamon', 'Vanilla', 'Caramel'],
    volume: 50,
    rating: 4.5,
    reviews: 156,
    inStock: true,
  },
  {
    id: '7',
    name: 'Aegean Blue',
    brand: 'Adventurous Spirit',
    price: 410000,
    image: 'https://images.unsplash.com/photo-1607112202415-ef6b0f7f18e2?w=500&h=500&fit=crop',
    description: 'Petualangan aromatik dengan cinnamon, cardamom, dan sandalwood.',
    category: 'unisex',
    family: 'Citrus',
    intensity: 'EDT',
    scent: ['Bergamot', 'Sea Salt', 'Aquatic'],
    volume: 100,
    rating: 4.6,
    reviews: 213,
    inStock: true,
  },
  {
    id: '8',
    name: 'Jasmine Garden',
    brand: 'Flores Beauty',
    price: 340000,
    image: 'https://images.unsplash.com/photo-1599499810694-b5ac4dd26d3f?w=500&h=500&fit=crop',
    description: 'Lembut dan feminine dengan bunga cherry dan white musk.',
    category: 'female',
    family: 'Floral',
    intensity: 'EDT',
    scent: ['Jasmine', 'Rose', 'Musk'],
    volume: 75,
    rating: 4.7,
    reviews: 287,
    inStock: true,
  },
  {
    id: '9',
    name: 'Forest Walk',
    brand: 'Nature\'s Essence',
    price: 360000,
    image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=500&h=500&fit=crop',
    description: 'Aroma hutan yang segar dengan kayu pinus dan moss.',
    category: 'male',
    family: 'Woody',
    intensity: 'EDP',
    scent: ['Pine', 'Moss', 'Cedar'],
    volume: 100,
    rating: 4.6,
    reviews: 178,
    inStock: true,
  },
  {
    id: '10',
    name: 'Lemon Zest',
    brand: 'Fresh Vibes',
    price: 300000,
    image: 'https://images.unsplash.com/photo-1571975414439-27d4b93f5f2d?w=500&h=500&fit=crop',
    description: 'Segar dan energik dengan lemon dan grapefruit.',
    category: 'unisex',
    family: 'Citrus',
    intensity: 'EDT',
    scent: ['Lemon', 'Grapefruit', 'Lime'],
    volume: 50,
    rating: 4.5,
    reviews: 145,
    inStock: true,
  },
  {
    id: '11',
    name: 'Honey Vanilla',
    brand: 'Sweet Dreams',
    price: 320000,
    image: 'https://images.unsplash.com/photo-1506755855726-85d82b8b34ec?w=500&h=500&fit=crop',
    description: 'Manis dan nyaman dengan madu dan vanila.',
    category: 'female',
    family: 'Vanilla',
    intensity: 'EDP',
    scent: ['Honey', 'Vanilla', 'Caramel'],
    volume: 75,
    rating: 4.8,
    reviews: 267,
    inStock: true,
    isBestseller: true,
  },
  {
    id: '12',
    name: 'Sandalwood Grace',
    brand: 'Oriental Luxury',
    price: 440000,
    image: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500&h=500&fit=crop',
    description: 'Elegan dan mewah dengan sandalwood dan musk.',
    category: 'female',
    family: 'Woody',
    intensity: 'EXTRAIT',
    scent: ['Sandalwood', 'Rose', 'Musk'],
    volume: 100,
    rating: 4.9,
    reviews: 312,
    inStock: true,
    isBestseller: true,
  },
  {
    id: '13',
    name: 'Citrus Splash',
    brand: 'Ocean Wave',
    price: 280000,
    image: 'https://images.unsplash.com/photo-1508737763-95b3d2e8c6b3?w=500&h=500&fit=crop',
    description: 'Menyegarkan dengan jeruk dan lada putih.',
    category: 'male',
    family: 'Citrus',
    intensity: 'EDT',
    scent: ['Orange', 'White Pepper', 'Musk'],
    volume: 75,
    rating: 4.4,
    reviews: 134,
    inStock: true,
  },
  {
    id: '14',
    name: 'Peach Blossom',
    brand: 'Garden Flowers',
    price: 350000,
    image: 'https://images.unsplash.com/photo-1590894903068-b0c9f1299c0c?w=500&h=500&fit=crop',
    description: 'Bunga peach yang lembut dan feminim.',
    category: 'female',
    family: 'Floral',
    intensity: 'EDT',
    scent: ['Peach', 'Rose', 'Vanilla'],
    volume: 75,
    rating: 4.6,
    reviews: 198,
    inStock: true,
  },
  {
    id: '15',
    name: 'Dark Leather',
    brand: 'Masculine Edge',
    price: 470000,
    image: 'https://images.unsplash.com/photo-1607112202415-ef6b0f7f18e2?w=500&h=500&fit=crop',
    description: 'Maskulin dan kuat dengan kulit dan tembakau.',
    category: 'male',
    family: 'Woody',
    intensity: 'EDP',
    scent: ['Leather', 'Tobacco', 'Cedar'],
    volume: 100,
    rating: 4.7,
    reviews: 243,
    inStock: true,
  },
  {
    id: '16',
    name: 'Chocolate Dreams',
    brand: 'Gourmand Fantasy',
    price: 330000,
    image: 'https://images.unsplash.com/photo-1599499810694-b5ac4dd26d3f?w=500&h=500&fit=crop',
    description: 'Indulgent cokelat dengan vanila dan nougat.',
    category: 'unisex',
    family: 'Vanilla',
    intensity: 'EDP',
    scent: ['Chocolate', 'Vanilla', 'Nougat'],
    volume: 50,
    rating: 4.5,
    reviews: 167,
    inStock: true,
  },
  {
    id: '17',
    name: 'Lily Whisper',
    brand: 'Delicate Florals',
    price: 370000,
    image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=500&h=500&fit=crop',
    description: 'Bunga lily yang halus dan feminin.',
    category: 'female',
    family: 'Floral',
    intensity: 'EDT',
    scent: ['Lily', 'Freesia', 'Musk'],
    volume: 75,
    rating: 4.7,
    reviews: 276,
    inStock: true,
  },
  {
    id: '18',
    name: 'Bergamot Joy',
    brand: 'Citrus Sunshine',
    price: 310000,
    image: 'https://images.unsplash.com/photo-1571975414439-27d4b93f5f2d?w=500&h=500&fit=crop',
    description: 'Bergamot segar dengan jeruk dan lada.',
    category: 'unisex',
    family: 'Citrus',
    intensity: 'EDT',
    scent: ['Bergamot', 'Lemon', 'White Pepper'],
    volume: 100,
    rating: 4.6,
    reviews: 189,
    inStock: true,
  },
  {
    id: '19',
    name: 'Vetiver Essence',
    brand: 'Earth Tones',
    price: 400000,
    image: 'https://images.unsplash.com/photo-1506755855726-85d82b8b34ec?w=500&h=500&fit=crop',
    description: 'Vetiver yang kuat dengan kayu cedar.',
    category: 'male',
    family: 'Woody',
    intensity: 'EDP',
    scent: ['Vetiver', 'Cedar', 'Musk'],
    volume: 100,
    rating: 4.8,
    reviews: 301,
    inStock: true,
  },
  {
    id: '20',
    name: 'Orchid Paradise',
    brand: 'Exotic Flowers',
    price: 420000,
    image: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500&h=500&fit=crop',
    description: 'Eksotis dengan anggrek dan jasmine.',
    category: 'female',
    family: 'Floral',
    intensity: 'EDP',
    scent: ['Orchid', 'Jasmine', 'Musk'],
    volume: 75,
    rating: 4.9,
    reviews: 378,
    inStock: true,
    isBestseller: true,
  },
  {
    id: '21',
    name: 'Caramel Toast',
    brand: 'Sweet Indulgence',
    price: 340000,
    image: 'https://images.unsplash.com/photo-1508737763-95b3d2e8c6b3?w=500&h=500&fit=crop',
    description: 'Manis seperti karamel toast dengan butter.',
    category: 'unisex',
    family: 'Vanilla',
    intensity: 'EDP',
    scent: ['Caramel', 'Butter', 'Vanilla'],
    volume: 50,
    rating: 4.6,
    reviews: 156,
    inStock: true,
  },
  {
    id: '22',
    name: 'Ocean Fresh',
    brand: 'Water Elements',
    price: 290000,
    image: 'https://images.unsplash.com/photo-1590894903068-b0c9f1299c0c?w=500&h=500&fit=crop',
    description: 'Kesegaran laut dengan garam dan alga.',
    category: 'unisex',
    family: 'Citrus',
    intensity: 'EDT',
    scent: ['Sea Salt', 'Seaweed', 'Aquatic'],
    volume: 100,
    rating: 4.5,
    reviews: 142,
    inStock: true,
  },
  {
    id: '23',
    name: 'Patchouli Soil',
    brand: 'Earthy Vibes',
    price: 380000,
    image: 'https://images.unsplash.com/photo-1607112202415-ef6b0f7f18e2?w=500&h=500&fit=crop',
    description: 'Patchouli tanah dengan cedar dan musk.',
    category: 'male',
    family: 'Woody',
    intensity: 'EXTRAIT',
    scent: ['Patchouli', 'Cedar', 'Musk'],
    volume: 100,
    rating: 4.7,
    reviews: 267,
    inStock: true,
  },
  {
    id: '24',
    name: 'Tulip Love',
    brand: 'Spring Flowers',
    price: 360000,
    image: 'https://images.unsplash.com/photo-1599499810694-b5ac4dd26d3f?w=500&h=500&fit=crop',
    description: 'Tulip yang lembut dan romantis.',
    category: 'female',
    family: 'Floral',
    intensity: 'EDT',
    scent: ['Tulip', 'Rose', 'Lily'],
    volume: 75,
    rating: 4.6,
    reviews: 213,
    inStock: true,
  },
  {
    id: '25',
    name: 'Ginger Spice',
    brand: 'Spicy Notes',
    price: 320000,
    image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=500&h=500&fit=crop',
    description: 'Jahe pedas dengan lada dan musk.',
    category: 'male',
    family: 'Vanilla',
    intensity: 'EDP',
    scent: ['Ginger', 'Pepper', 'Cardamom'],
    volume: 100,
    rating: 4.5,
    reviews: 174,
    inStock: true,
  },
  {
    id: '26',
    name: 'Lavender Mist',
    brand: 'Herbal Dreams',
    price: 300000,
    image: 'https://images.unsplash.com/photo-1571975414439-27d4b93f5f2d?w=500&h=500&fit=crop',
    description: 'Lavender menenangkan dengan herbal notes.',
    category: 'unisex',
    family: 'Floral',
    intensity: 'EDT',
    scent: ['Lavender', 'Herb', 'Musk'],
    volume: 75,
    rating: 4.7,
    reviews: 298,
    inStock: true,
  },
  {
    id: '27',
    name: 'Tropical Fruits',
    brand: 'Exotic Paradise',
    price: 330000,
    image: 'https://images.unsplash.com/photo-1506755855726-85d82b8b34ec?w=500&h=500&fit=crop',
    description: 'Buah tropis dengan mangga dan pineapple.',
    category: 'female',
    family: 'Citrus',
    intensity: 'EDT',
    scent: ['Mango', 'Pineapple', 'Coconut'],
    volume: 50,
    rating: 4.6,
    reviews: 187,
    inStock: true,
  },
  {
    id: '28',
    name: 'Black Oud',
    brand: 'Luxury Oriental',
    price: 550000,
    image: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500&h=500&fit=crop',
    description: 'Oud hitam premium dengan rose.',
    category: 'male',
    family: 'Woody',
    intensity: 'EXTRAIT',
    scent: ['Oud', 'Rose', 'Patchouli'],
    volume: 50,
    rating: 4.9,
    reviews: 423,
    inStock: true,
    isBestseller: true,
  },
  {
    id: '29',
    name: 'Soft Musk',
    brand: 'Delicate Touch',
    price: 280000,
    image: 'https://images.unsplash.com/photo-1508737763-95b3d2e8c6b3?w=500&h=500&fit=crop',
    description: 'Musk lembut dengan sedikit floral.',
    category: 'female',
    family: 'Floral',
    intensity: 'EDT',
    scent: ['Musk', 'Rose', 'Vanilla'],
    volume: 50,
    rating: 4.5,
    reviews: 145,
    inStock: true,
  },
  {
    id: '30',
    name: 'Lime Cooler',
    brand: 'Fresh Breeze',
    price: 270000,
    image: 'https://images.unsplash.com/photo-1590894903068-b0c9f1299c0c?w=500&h=500&fit=crop',
    description: 'Jeruk nipis segar dengan lemon.',
    category: 'unisex',
    family: 'Citrus',
    intensity: 'EDT',
    scent: ['Lime', 'Lemon', 'Green Leaf'],
    volume: 100,
    rating: 4.4,
    reviews: 123,
    inStock: true,
  },
  {
    id: '31',
    name: 'Coffee & Cocoa',
    brand: 'Morning Glory',
    price: 370000,
    image: 'https://images.unsplash.com/photo-1607112202415-ef6b0f7f18e2?w=500&h=500&fit=crop',
    description: 'Kopi dan cokelat untuk pagi yang sempurna.',
    category: 'male',
    family: 'Vanilla',
    intensity: 'EDP',
    scent: ['Coffee', 'Cocoa', 'Vanilla'],
    volume: 100,
    rating: 4.7,
    reviews: 289,
    inStock: true,
  },
  {
    id: '32',
    name: 'Rose Gold',
    brand: 'Precious Moments',
    price: 410000,
    image: 'https://images.unsplash.com/photo-1599499810694-b5ac4dd26d3f?w=500&h=500&fit=crop',
    description: 'Rose emas yang berharga.',
    category: 'female',
    family: 'Floral',
    intensity: 'EDP',
    scent: ['Rose', 'Gold Flower', 'Musk'],
    volume: 75,
    rating: 4.8,
    reviews: 334,
    inStock: true,
    isBestseller: true,
  },
  {
    id: '33',
    name: 'Mint Breeze',
    brand: 'Cool Vibes',
    price: 260000,
    image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=500&h=500&fit=crop',
    description: 'Mint segar dengan eucalyptus.',
    category: 'unisex',
    family: 'Citrus',
    intensity: 'EDT',
    scent: ['Mint', 'Eucalyptus', 'Lemon'],
    volume: 100,
    rating: 4.6,
    reviews: 156,
    inStock: true,
  },
  {
    id: '34',
    name: 'Amber Dreams',
    brand: 'Warm Nights',
    price: 390000,
    image: 'https://images.unsplash.com/photo-1571975414439-27d4b93f5f2d?w=500&h=500&fit=crop',
    description: 'Amber hangat dengan kayu.',
    category: 'female',
    family: 'Vanilla',
    intensity: 'EDP',
    scent: ['Amber', 'Wood', 'Vanilla'],
    volume: 75,
    rating: 4.7,
    reviews: 267,
    inStock: true,
  },
  {
    id: '35',
    name: 'Teak Wood',
    brand: 'Natural Elements',
    price: 430000,
    image: 'https://images.unsplash.com/photo-1506755855726-85d82b8b34ec?w=500&h=500&fit=crop',
    description: 'Kayu teak alami dengan musk.',
    category: 'male',
    family: 'Woody',
    intensity: 'EDP',
    scent: ['Teak', 'Sandalwood', 'Musk'],
    volume: 100,
    rating: 4.8,
    reviews: 312,
    inStock: true,
    isBestseller: true,
  },
  {
    id: '36',
    name: 'Magnolia Crown',
    brand: 'Botanical Garden',
    price: 400000,
    image: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500&h=500&fit=crop',
    description: 'Magnolia royal dengan floral.',
    category: 'female',
    family: 'Floral',
    intensity: 'EDP',
    scent: ['Magnolia', 'Gardenia', 'Musk'],
    volume: 75,
    rating: 4.9,
    reviews: 401,
    inStock: true,
    isBestseller: true,
  },
  {
    id: '37',
    name: 'Tangerine Pop',
    brand: 'Sunny Days',
    price: 300000,
    image: 'https://images.unsplash.com/photo-1508737763-95b3d2e8c6b3?w=500&h=500&fit=crop',
    description: 'Jeruk mandarin yang ceria.',
    category: 'unisex',
    family: 'Citrus',
    intensity: 'EDT',
    scent: ['Tangerine', 'Orange', 'Lime'],
    volume: 50,
    rating: 4.5,
    reviews: 167,
    inStock: true,
  },
  {
    id: '38',
    name: 'Cinnamon Bark',
    brand: 'Spice Master',
    price: 350000,
    image: 'https://images.unsplash.com/photo-1590894903068-b0c9f1299c0c?w=500&h=500&fit=crop',
    description: 'Kayu manis pedas dengan vanila.',
    category: 'male',
    family: 'Vanilla',
    intensity: 'EDP',
    scent: ['Cinnamon', 'Vanilla', 'Wood'],
    volume: 100,
    rating: 4.6,
    reviews: 234,
    inStock: true,
  },
  {
    id: '39',
    name: 'Hyacinth Dream',
    brand: 'Garden Essence',
    price: 360000,
    image: 'https://images.unsplash.com/photo-1607112202415-ef6b0f7f18e2?w=500&h=500&fit=crop',
    description: 'Bunga hyacinth yang indah.',
    category: 'female',
    family: 'Floral',
    intensity: 'EDT',
    scent: ['Hyacinth', 'Violet', 'Leaf'],
    volume: 75,
    rating: 4.7,
    reviews: 278,
    inStock: true,
  },
  {
    id: '40',
    name: 'White Pepper',
    brand: 'Spicy Edge',
    price: 310000,
    image: 'https://images.unsplash.com/photo-1599499810694-b5ac4dd26d3f?w=500&h=500&fit=crop',
    description: 'Lada putih dengan herbal.',
    category: 'male',
    family: 'Citrus',
    intensity: 'EDT',
    scent: ['White Pepper', 'Herb', 'Musk'],
    volume: 100,
    rating: 4.6,
    reviews: 189,
    inStock: true,
  },
  {
    id: '41',
    name: 'Butterscotch',
    brand: 'Candy Land',
    price: 320000,
    image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=500&h=500&fit=crop',
    description: 'Butterscotch manis dengan vanilla.',
    category: 'unisex',
    family: 'Vanilla',
    intensity: 'EDP',
    scent: ['Butterscotch', 'Vanilla', 'Caramel'],
    volume: 50,
    rating: 4.7,
    reviews: 245,
    inStock: true,
  },
  {
    id: '42',
    name: 'Iris Beauty',
    brand: 'Flower Kingdom',
    price: 380000,
    image: 'https://images.unsplash.com/photo-1571975414439-27d4b93f5f2d?w=500&h=500&fit=crop',
    description: 'Iris indah dengan violet.',
    category: 'female',
    family: 'Floral',
    intensity: 'EDP',
    scent: ['Iris', 'Violet', 'Musk'],
    volume: 75,
    rating: 4.8,
    reviews: 312,
    inStock: true,
  },
  {
    id: '43',
    name: 'Grapefruit Sunrise',
    brand: 'Morning Scents',
    price: 280000,
    image: 'https://images.unsplash.com/photo-1506755855726-85d82b8b34ec?w=500&h=500&fit=crop',
    description: 'Grapefruit segar untuk pagi.',
    category: 'unisex',
    family: 'Citrus',
    intensity: 'EDT',
    scent: ['Grapefruit', 'Lemon', 'Herb'],
    volume: 100,
    rating: 4.5,
    reviews: 156,
    inStock: true,
  },
  {
    id: '44',
    name: 'Hazelnut Delight',
    brand: 'Nut House',
    price: 340000,
    image: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500&h=500&fit=crop',
    description: 'Hazelnut lezat dengan cokelat.',
    category: 'male',
    family: 'Vanilla',
    intensity: 'EDP',
    scent: ['Hazelnut', 'Cocoa', 'Vanilla'],
    volume: 100,
    rating: 4.6,
    reviews: 201,
    inStock: true,
  },
  {
    id: '45',
    name: 'Violet Mist',
    brand: 'Purple Dreams',
    price: 370000,
    image: 'https://images.unsplash.com/photo-1508737763-95b3d2e8c6b3?w=500&h=500&fit=crop',
    description: 'Violet misty dengan herbal.',
    category: 'female',
    family: 'Floral',
    intensity: 'EDT',
    scent: ['Violet', 'Herbal', 'Musk'],
    volume: 75,
    rating: 4.7,
    reviews: 267,
    inStock: true,
  },
  {
    id: '46',
    name: 'Pink Grapefruit',
    brand: 'Pink Paradise',
    price: 290000,
    image: 'https://images.unsplash.com/photo-1590894903068-b0c9f1299c0c?w=500&h=500&fit=crop',
    description: 'Grapefruit pink yang segar.',
    category: 'female',
    family: 'Citrus',
    intensity: 'EDT',
    scent: ['Pink Grapefruit', 'Lemon', 'Musk'],
    volume: 50,
    rating: 4.6,
    reviews: 178,
    inStock: true,
  },
  {
    id: '47',
    name: 'Ebony Wood',
    brand: 'Dark Essence',
    price: 460000,
    image: 'https://images.unsplash.com/photo-1607112202415-ef6b0f7f18e2?w=500&h=500&fit=crop',
    description: 'Kayu ebony gelap dengan oud.',
    category: 'male',
    family: 'Woody',
    intensity: 'EXTRAIT',
    scent: ['Ebony', 'Oud', 'Patchouli'],
    volume: 100,
    rating: 4.8,
    reviews: 289,
    inStock: true,
    isBestseller: true,
  },
  {
    id: '48',
    name: 'Peony Paradise',
    brand: 'Flower Festival',
    price: 400000,
    image: 'https://images.unsplash.com/photo-1599499810694-b5ac4dd26d3f?w=500&h=500&fit=crop',
    description: 'Peony surga dengan bunga.',
    category: 'female',
    family: 'Floral',
    intensity: 'EDP',
    scent: ['Peony', 'Rose', 'Lily'],
    volume: 75,
    rating: 4.9,
    reviews: 356,
    inStock: true,
    isBestseller: true,
  },
];

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getProductsByCategory(category: string): Product[] {
  return products.filter((p) => p.category === category);
}

export function searchProducts(query: string): Product[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];

  const words = q.split(/\s+/).filter(Boolean);

  return products.filter((p) => {
    const haystack = [
      p.name,
      p.brand,
      p.description,
      p.family,
      p.intensity,
      p.category,
      ...p.scent,
    ]
      .join(' ')
      .toLowerCase();

    return words.every((word) => haystack.includes(word));
  });
}

export function getSuggestedProducts(list: Product[], limit = 4): Product[] {
  return [...list]
    .sort((a, b) => (b.isBestseller ? 1 : 0) - (a.isBestseller ? 1 : 0) || b.rating - a.rating)
    .slice(0, limit);
}

export function searchProductsInList(query: string, list: Product[]): Product[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];

  const words = q.split(/\s+/).filter(Boolean);

  return list.filter((p) => {
    const haystack = [
      p.name,
      p.brand,
      p.description,
      p.family,
      p.intensity,
      p.category,
      ...p.scent,
    ]
      .join(' ')
      .toLowerCase();

    return words.every((word) => haystack.includes(word));
  });
}

export async function fetchProducts(): Promise<Product[]> {
  const response = await fetch('/api/products', { cache: 'no-store' });
  if (!response.ok) throw new Error('Gagal mengambil produk');
  const data = await response.json();
  return data.map((p: Product) => ({
    ...p,
    id: String(p.id),
    inStock: Boolean(p.inStock),
    isBestseller: Boolean(p.isBestseller),
    scent: Array.isArray(p.scent) ? p.scent : [],
  }));
}

export async function fetchProductById(id: string): Promise<Product | null> {
  const response = await fetch(`/api/products/${id}`);
  if (response.status === 404) return null;
  if (!response.ok) throw new Error('Gagal mengambil produk');
  const p = await response.json();
  return {
    ...p,
    id: String(p.id),
    inStock: Boolean(p.inStock),
    isBestseller: Boolean(p.isBestseller),
    scent: Array.isArray(p.scent) ? p.scent : [],
  };
}
